# Generated by Django 5.0.4 on 2024-04-24 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados',
            name='tipo',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('usuario', 'Usuário')], default='usuario', max_length=50),
        ),
    ]
