# Generated by Django 5.0.4 on 2024-04-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_dados_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('endereco', models.CharField(max_length=255)),
                ('tipo_de_lixo', models.CharField(max_length=100)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='ocorrencias/')),
            ],
        ),
    ]
