# Generated by Django 5.0.2 on 2024-04-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_ocorrencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/'),
        ),
    ]
