# Generated by Django 5.0.6 on 2024-06-07 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_dados_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dados',
            old_name='usuario',
            new_name='nome',
        ),
    ]
