# Generated by Django 5.0.6 on 2024-06-08 19:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_rename_usuario_dados_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
