# Generated by Django 5.0.6 on 2024-06-08 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_ocorrencia_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('reciclagem', 'Reciclagem'), ('orientacoes', 'Orientações'), ('praticas', 'Práticas')], max_length=20)),
                ('texto', models.TextField()),
            ],
        ),
    ]
