# Generated by Django 5.0.6 on 2024-06-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_dica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dica',
            name='tipo',
            field=models.CharField(choices=[('reciclagem', 'Reciclagem'), ('orientacoes', 'Orientações'), ('cuidados', 'Cuidados')], max_length=20),
        ),
    ]
