# Generated by Django 5.0.6 on 2024-06-08 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_dica_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.ocorrencia')),
            ],
        ),
    ]
