# Generated by Django 5.0.6 on 2024-06-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_alerta'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='acao',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='local',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='alerta',
            name='tipo',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
