# Generated by Django 5.0.6 on 2024-06-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_alerta_acao_alerta_local_alerta_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('mensagem', models.TextField()),
                ('avaliacao', models.IntegerField()),
            ],
        ),
    ]
