# Generated by Django 5.0.6 on 2024-06-10 18:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_avaliacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('avaliacao', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('observacoes', models.TextField()),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.ocorrencia')),
            ],
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
