name: Build and deploy Python app to Azure Web App - EcoPay

on:
  push:
    branches:
      - prod3
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20 # Timeout de 20 minutos para o job

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r ./ecopay1/requirements.txt

      - name: Cleaning testing files
        run: |
          rm ./ecopay1/db.sqlite3
          rm .env
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip ecopay1
          zip -r release.zip venv

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 20 # Timeout de 20 minutos para o job
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_166822A918F6411A8400746A3C62DA9E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2FB498B51EBD44F09F670747A5904E43 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BAC27104860C4607AB17360003443973 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'EcoPay'
          slot-name: 'Production'
          package: release.zip
